### ISSUE TITLE
Android AboutPage image

### ISSUE THREAD

**Issue by mlach88** [mlach88/StockTrends#13]
stocktrendstrans.png needs to be copied into Droid --> Resources --> Drawable

I'm still having an issue about the sizing but at least the Logo shows up if we move the .png

**Comment by fletchy95** [comment]
Ok we can discuss after class.

**Comment by fletchy95** [comment]
Was this fixed @mlach88 ?  Can you confirm?

**Comment by fletchy95** [comment]
@mlach88 pull JackV2 branch.  I added it in the file.  
For future reference you do the following:
    1) Locate Folder where you want to add the file
    2) Right click on that folder and select 'Add Files' or 'Add File'
    3) Locate and add the file
    4 (optional maybe)) A seperate box may pop up that asks you to move the file, copy the file or create a link to the file, I typically select 'Copy The File' or 'Move the file' depending on what I need.

**Comment by mlach88** [comment]
thanks jack
