### ISSUE TITLE
Approve App

### ISSUE THREAD

**Issue by fletchy95** [mlach88/StockTrends#19]
Hey guys I want you to just comment on this post.  You commenting on this post will say basically say the App is good, and It is fine to upload to blackboard for final submission.  

I approve for upload, @mlach88 and @joseph-graham1 , is it good to go?

**Comment by fletchy95** [comment]
Once you guys approve app I'll pull the app in to master and release it.  So if you want to check the app before approving, take a look at branch JackV2

**Comment by joseph-graham1** [comment]
Yup, the app looks good to me!

**Comment by fletchy95** [comment]
Sweet just need @mlach88.  Whenever you good I'll do the final steps.

PS Leave issue open until I complete the pull request.

**Comment by mlach88** [comment]
@fletchy95 app looks really great, you did a great job!

**Comment by fletchy95** [comment]
Awesome!

**Comment by fletchy95** [comment]
Pull request completed.
